# Generated by Django 5.0.6 on 2024-06-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('admission_start_date', models.DateField(blank=True, null=True)),
                ('admission_end_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(choices=[('GA', 'Greater Accra'), ('NR', 'Northern'), ('AS', 'Ashanti'), ('WR', 'Western'), ('VR', 'Volta'), ('ER', 'Eastern'), ('UW', 'Upper West'), ('UE', 'Upper East'), ('SR', 'Savannah'), ('NE', 'North East'), ('BE', 'Bono East'), ('OR', 'Oti'), ('AR', 'Ahafo'), ('BR', 'Bono'), ('WN', 'Western North')])),
            ],
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField(blank=True)),
                ('domestic_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('international_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mode_of_teaching', models.CharField(choices=[('FF', 'Face-to-face'), ('OL', 'Online'), ('BL', 'Blender Learning')])),
                ('time_of_study', models.CharField(choices=[('FT', 'Full Time'), ('WO', 'Weekend Only'), ('MO', 'Morning Only'), ('AO', 'Afternoon Only'), ('EO', 'Evening Only'), ('OL', 'Online Only')])),
                ('duration_of_study', models.DurationField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.campus')),
                ('certificates', models.ManyToManyField(to='schools.certificatetype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.course')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution_type', models.CharField(choices=[('UN', 'University'), ('TU', 'Technical University'), ('NT', 'Non-tertiary'), ('VT', 'Vocation/Technical Institution'), ('PI', 'Professional Institute (Chartered bodies)'), ('SC', 'Short Courses (CPD)')], default='UN', max_length=2)),
                ('ownership_type', models.CharField(choices=[('PB', 'Public'), ('PV', 'PRIVATE')], default='PB')),
                ('enable', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.institution'),
        ),
    ]
