# Generated by Django 5.0.6 on 2024-06-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'campus'},
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
