# Generated by Django 5.0.6 on 2024-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
