# Generated by Django 5.0.6 on 2024-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_institution_owner_alter_campus_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='type_of_student',
            field=models.CharField(default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseprofile',
            name='duration_of_study',
            field=models.CharField(choices=[('Y', 'Years'), ('M', 'Months'), ('W', 'Weeks'), ('D', 'Days')], max_length=1),
        ),
        migrations.AlterField(
            model_name='institution',
            name='ownership_type',
            field=models.CharField(choices=[('PB', 'Public'), ('PV', 'Private')], default='PB'),
        ),
    ]
