# Generated by Django 5.0.6 on 2024-06-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_lead_type_of_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprofile',
            old_name='duration_of_study',
            new_name='duration_of_study_unit',
        ),
    ]
