# Generated by Django 5.0.6 on 2024-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_rename_duration_of_study_courseprofile_duration_of_study_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprofile',
            name='duration_of_study',
            field=models.IntegerField(default=1),
        ),
    ]
